version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3366:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leadquizzes

  admin:
    image: adminer
    ports:
      - "8080:8080"
